###
post http://localhost:4000/api/user/login
Content-Type: application/json

{
    "email":"yes@gmail.com",
    "password":"234w"
}
###
post http://localhost:4000/api/user/login
Content-Type: application/json

{
    "email":"visitor2@gmail.com",
    "password":"234w"
}

###
get http://localhost:4000/api/product/all/products

###
get http://localhost:4000/api/user/all/users

###
get http://localhost:4000/api/user/logout

